### ISSUE TITLE
Bug on delete plugin

### ISSUE THREAD

**Issue by artras** [adrenth/redirect#30] opened 2016-10-15 15:53 UTC
![bug_red](https://cloud.githubusercontent.com/assets/5288244/19411345/b3bb4022-9308-11e6-9472-54742aa2202b.PNG)

**Comment by adrenth** [comment] 2016-10-16 08:31
Hey thanks for reporting this issue. But I can't reproduce this on my local machine.
Which version of PHP (looks like php7) and MySQL are you using?

**Comment by artras** [comment] 2016-10-16 08:38
5.6.33 - MySQL Community Server (GPL)
7.0 - ea-php70 on WHM

**Comment by adrenth** [comment] 2016-11-23 19:34
Cannot reproduce. Closing this issue for now.

**Closed by adrenth** 2016-11-23 19:34 UTC
